avatar: "https://secure.gravatar.com/avatar/#"
logo: "http://rubyonrails.org/"
avatar_mail: "http://gravatar.com/emails"
remember: 1
name_maximum: 50
email_maximum: 255
password_maximum_length: 6
remember: 1
admin: 1
normal: 0
per_page: 10
avatar_size_default: 80
avatar_size: 30
avatar_size_user: 50
naming_for_action_follow:
  -following
  -followers
